name 'gehel-carbon'
version '1.0.0'

author 'Guillaume Lederrey'
license 'Apache2'
project_page ''
source 'https://github.com/gehel/puppet-carbon'
summary 'Puppet module for carbon'
description 'This module installs and manages carbon. Check README for details.'
dependency 'example42/puppi', '>=2.0.0'
dependency 'example42/firewall', '>=2.0.0'
dependency 'example42/monitor', '>=2.0.0'
